hdl/bazel_rules_hdl

- BUILD
- WORKSPACE
- dependency_support/com_google_skywater_pdk/BUILD
- dependency_support/com_google_skywater_pdk/bundled.BUILD.bazel
- dependency_support/com_google_skywater_pdk/cell_libraries.bzl
- dependency_support/com_google_skywater_pdk/com_google_skywater_pdk.bzl
- dependency_support/com_google_skywater_pdk/declare_cell_library.bzl
- dependency_support/com_google_skywater_pdk/liberty_wrapper.py
- dependency_support/pip_requirements.txt
- init.bzl
There's no issue for this but @mithro said in private chat that this would be useful to have in this repo.
Note: The Skywater PDK has Python pip dependencies. They are loaded using rules_python, which requires a two-step loading process which AFAIK cannot be hidden from users of bazel_rules_hdl. Bazel workspaces that use bazel_rules_hdl will need to first load it, and then call an init method. I created `init.bzl` for this purpose.
> Add Skywater PDK

- cloudbuild.yaml
Before this PR hdl-bazel-rules-hdl-pr works, but not hdl-bazel-rules-hdl-push.
> Fix hdl-bazel-rules-hdl-push CI configuration

- .bazelrc
I tried using Buildbuddy for this, but uploads of some large artifacts time out and fail the whole build. Hopefully GCS will perform better here, either by not having the timeout, or by being faster, let's see.
> Enable Bazel cache backed by Google Cloud Storage

- dependency_support/org_fftw/BUILD
- dependency_support/org_fftw/bundled.BUILD.bazel
- dependency_support/org_fftw/link_test.cc
By default this happens for tests but not for cc_binary targets.
> Fix errors when linking against the shared library version of FFTW

- dependency_support/org_gnu_m4/bundled.BUILD.bazel
Tested with XLS simulations on Ubuntu 18.04 and 20.04.
> Apparent fix for Ubuntu 20.10

- dependency_support/com_github_westes_flex/bundled.BUILD.bazel
- dependency_support/org_gnu_gnulib/config-darwin.h
**com_github_westes_flex: drop unnecessary locale bits**
Dropped `ENABLE_NLS`, `HAVE_GETTEXT` and other locale bits from `defs`. 
```
Users most likely won't benefit from localized messages.
This change removes an unwanted dependency on locale libs of the
system, and makes "flex" compile on platforms that don't have one
and platforms that have different-than-expected one.
```
**org_gnu_gnulib: add header declarations of obstack for macOS**
Fixes `implicit declaration of function` errors on macOS.
> com_github_westes_flex, org_gnu_gnulib: portability improvements

- dependency_support/at_clifford_yosys/bundled.BUILD.bazel
- dependency_support/at_clifford_yosys/yosys.bzl
- dependency_support/com_google_skywater_pdk/declare_cell_library.bzl
- synthesis/BUILD
- synthesis/build_defs.bzl
- synthesis/tests/BUILD
- synthesis/tests/verilog_adder.v
- verilog/BUILD
- verilog/providers.bzl
This PR introduces two major concepts
* verilog_library and its associated providers.
* synthesize_rtl which takes a PDK and generates a synthesized
netlist.
Both rules generate consumable providers that can be used by downstream
rules.
> Synthesis: Added the ability to use yosys to synthesize verilog_library rules

- dependency_support/at_clifford_yosys/bundled.BUILD.bazel
- dependency_support/net_invisible_island_ncurses/net_invisible_island_ncurses.bzl
- dependency_support/org_gnu_readline/org_gnu_readline.bzl
- synthesis/build_defs.bzl
This change allows you to drop the direct dependency on abc in the synthesis rule.
> [synthesis] Fix tool imports of abc in yosys

- dependency_support/org_pcre_ftp/org_pcre_ftp.bzl
In the download section, https://www.pcre.org/ makes it clear that ftp.pcre.org is down permanently, so we need a different source for pcre-8.44. Unlike pcre2, we can't get pcre from GitHub because it is no longer maintained.
In the bigger picture, we probably want to replace pcre with something else now that it is end-of-life (or stop using it the way Tensorflow did: https://github.com/tensorflow/tensorflow/pull/49023). That being said, getting the same pcre tarball from somewhere else will at least unbreak our CI so it's worth doing.
> Replace ftp.pcre.org with a different source for pcre 8.44 

- place_and_route/BUILD
- synthesis/BUILD
This uses the deprecated pkg_tar instead of rules_pkg for Bazel 3.5 compatibility.
This is the Bazel 3.5 compatible version of https://github.com/hdl/bazel_rules_hdl/pull/60
> Add tar file targets that package openroad and yosys with their runfiles

- tools/test_everything.py
This makes is easier to test with different version of bazel on the same machine.
> Add an environment-variable override for bazel to test_everything.py

- cloudbuild.yaml
This is kind of a hack to upgrade bazel to 4.2.1. When a new Bazel Docker container is released we should remove this commit, and upgrade the docker container instead.
See https://github.com/bazelbuild/continuous-integration/issues/1060
> Update Bazel to 4.2.1

- place_and_route/open_road.bzl
This addresses some errors users were seeing when running slight
variations on existing configurations.
It's caused because by default the rules use the hash of the inputs to name intermediate outputs which can often be the same name.
> place_and_route: Fixes conflict error when multiple targets with varying parameters

- place_and_route/private/detailed_routing.bzl
Liberty should be read to make the flow complete. For example, report_power or report_design_area commands cannot be executed with this.
> Read liberty in detailed_routing bzl

- dependency_support/at_clifford_yosys/at_clifford_yosys.bzl
- dependency_support/at_clifford_yosys/bundled.BUILD.bazel
- dependency_support/at_clifford_yosys/yosys.patch
- dependency_support/net_invisible_island_ncurses/bundled.BUILD.bazel
at_clifford_yosys: replace ternary "-D" with patch (fix #73):
```
There seems to be a regression (or behavior change) with Bazel 4.2.2 in string escaping or copts sanitization.
```
ncurses: cp with "-f" to deal with unsandboxed cases:
```
Fixes: "cp: cannot create regular file './make_hash': File exists"
This issue only happens when Bazel runs with unsandboxed strategies
like "local" or "standalone".
On some platforms (e.g. macOS), debug symbols of compiled binaries
are stored in separate file(s). Bazel fails to preserve those files
in sandboxed mode (default). In other cases, we may wish to inspect
the intermediate files generated during an action. As such, it is
often necessary to run Bazel with unsandboxed strategies.
```
> at_clifford_yosys: replace ternary "-D" with patch, ncurses: cp with "-f" to deal with unsandboxed cases 

- place_and_route/open_road.bzl
- place_and_route/private/floorplan.bzl
- place_and_route/private/global_routing.bzl
Remove the {power|area}_results OpenRoadInfo fields. Moving forward, the more precise fields should be used instead.
> Remove the {power|area}_results OpenRoadInfo fields. Moving forward, the more precise fields should be used instead.

- dependency_support/at_clifford_yosys/at_clifford_yosys.bzl
This doesn't fix the determinism issue reported [here](https://github.com/YosysHQ/yosys/issues/3184), but I think it is valuable for Yosys to be more up-to-date regardless.
> Update dependency to Yosys-0.13

- flows/analysis/BUILD.bazel
- flows/analysis/characterize.tcl
- flows/analysis/simple_synth.tcl
- flows/openroad/build_defs.bzl
These are analysis binaries that take input RTL and put the slack in ps (positive or negative) in a "slack_ps" metric, to be compatible with process characterization using the characterization server at https://github.com/google/xls/tree/main/xls/synthesis/openroad
> Add analysis binaries to support XLS Sky130 and ASAP7 process characterization

- dependency_support/org_gnu_gnulib/org_gnu_gnulib.bzl
- dependency_support/org_gnu_gnulib/stop_using_sigstksz.patch
The following error occurred on systems with glibc 2.34+:
```
external/org_gnu_gnulib/lib/c-stack.c:55:26: error: function-like macro 'sysconf' is not defined
^
/usr/include/bits/sigstksz.h:28:19: note: expanded from macro 'SIGSTKSZ'
^
external/org_gnu_gnulib/lib/c-stack.c:141:8: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
char buffer[SIGSTKSZ];
```
It turns out "MINSIGSTKSZ and SIGSTKSZ are no longer constant on
Linux, MINSIGSTKSZ is redefined to sysconf(_SC_MINSIGSTKSZ) and
SIGSTKSZ is redefined to sysconf (_SC_SIGSTKSZ)" [1].
This creates an issue for cases where constant value is expected, but
luckily, upstream already has a patch (coreutils/gnulib@f9e2b20a12).
This change backports the patch to our version of gnulib. …
> org_gnu_gnulib: backport "c-stack: stop using SIGSTKSZ"

- dependency_support/com_icarus_iverilog/bundled.BUILD.bazel
Adds a Bazel `select` for Darwin to specify the OSX-default definition
of the "--export-dynamic/-export_dynamic" linker flag.
Encountered while building iverilog on an M1 Mac. Tested in that environment, but not in Linux and/or on x86.
> Adds support for the OSX-default Clang.

- dependency_support/com_google_absl/com_google_absl.bzl
There are compile warnings for older abseil versions in OSX (clang)
> upgrade abseil to latest LTS

- dependency_support/at_clifford_yosys/at_clifford_yosys.bzl
- dependency_support/at_clifford_yosys/bundled.BUILD.bazel
- dependency_support/at_clifford_yosys/yosys.patch
Signed-off-by: Tim Callahan <tcal@google.com>
> Bump Yosys to 0.22, incl version string and patch.

- dependency_support/copy.bzl
- dependency_support/org_gnu_bison/bundled.BUILD.bazel
- dependency_support/org_gnu_gnulib/org_gnu_gnulib.bzl
- dependency_support/org_gnu_m4/bundled.BUILD.bazel
This was caused by a weird configuration for config.h in the gnulib package. I added configurability to the version information so that it gives downstream packages the option to override the redacted option.
> Fixes redacted version info in bison and m4

- synthesis/build_defs.bzl
- synthesis/synth.tcl
These changes re-enable the Yosys footer to print out run time and memory usage.
Signed-off-by: tcal-x <tcal@google.com>
> Collect more metrics using synth.tcl: flops, logic levels, runtime.

- place_and_route/open_road.bzl
- synthesis/build_defs.bzl
Synthesis: Adds new synthesis_binary rule
The new rules allows you to get a binary version of the synthesize_rtl rule.
This version is self contained, and can be run outside the context of bazel
> Synthesis: Adds new synthesis_binary rule

- dependency_support/com_icarus_iverilog/bundled.BUILD.bazel
> Use `-no_pie` for darwin builds

- vivado/defs.bzl
When using the vivado_flow macro the naming of the routing report is currently something like
`my_design_route_synth_timing.rpt`
Changing to:
`my_design_route_timing.rpt`
> Fix report naming. 

- dependency_support/org_theopenroadproject/bundled.BUILD.bazel
- static_timing/BUILD
- static_timing/build_defs.bzl
- static_timing/sta.tcl
- synthesis/tests/BUILD
Rules to run opensta to get longest path.
Uses a default "sta.tcl" script that can be overridden.
> Rules to run opensta to get longest path.

- dependency_support/com_icarus_iverilog/dummy.sh
- dependency_support/com_icarus_iverilog/hello_verilog_test.sh
- dependency_support/com_icarus_iverilog/iverilog.sh
- dependency_support/com_icarus_iverilog/vvp.sh
In a pure environment (such as nixos), the hard-coded path /bin/bash might not exist. The recommended way in the Unix environment is to use /usr/bin/env
Signed-off-by: Henner Zeller <h.zeller@acm.org>
> Don't hardcode assumed path to /bin/bash, use /usr/bin/env bash instead.

- place_and_route/private/floorplan.bzl
Rules to run opensta to get longest path.
Uses a default "sta.tcl" script that can be overridden.
> Tie cells: use 'insert_tiecells' in floorplan script.

- dependency_support/pip_requirements.txt
JWT transitively includes cryptography, which seems not to build successfully on new-ish macs. Bumping the version seems to resolve this.
> Bump requirements.txt

- dependency_support/org_theopenroadproject/bundled.BUILD.bazel
- static_timing/sta.tcl
- synthesis/synth.tcl
Move commands in StaApp into sta:: namespace to match behavior of external builds.
> Move commands in StaApp into sta:: namespace to match behavior of external builds.

- dependency_support/com_google_skywater_pdk/build_defs.bzl
Update so that sky130_fd_sc_hd:sky130_fd_sc_hd returns the default corner Liberty file in its DefaultInfo.
> Update so that sky130_fd_sc_hd:sky130_fd_sc_hd returns the default corner Liberty file in its DefaultInfo.

- dependency_support/boost/add_python.patch
- dependency_support/boost/boost.bzl
- dependency_support/boost/libbacktrace.patch
- dependency_support/com_github_gabime_spdlog/com_github_gabime_spdlog.bzl
This PR is the second one in the PR chain that consists of:
* [1/3] https://github.com/hdl/bazel_rules_hdl/pull/167
* [2/3] https://github.com/hdl/bazel_rules_hdl/pull/164
* [3/3] https://github.com/hdl/bazel_rules_hdl/pull/165
Each of the following PRs depend on previous ones which means that the correct merging order is: 
https://github.com/hdl/bazel_rules_hdl/pull/167 -> https://github.com/hdl/bazel_rules_hdl/pull/164 -> https://github.com/hdl/bazel_rules_hdl/pull/165
I will rebase the PRs one at the time as they are merged in order to avoid conflicts.
This PR bumps the build rules for boost effectively bumping boost dependency to v1.82.
Due to rename (BUILD.boost -> boost.BUILD) and small changes in the renamed file also the patches had to be updated.
Additionally, `boost_library` for …
> dependency_support: boost: bump boost to v1.82

- dependency_support/boost/libbacktrace.patch
This PR is the third and the last one in PR chain that consists of:
* [1/3] https://github.com/hdl/bazel_rules_hdl/pull/167
* [2/3] https://github.com/hdl/bazel_rules_hdl/pull/164
* [3/3] https://github.com/hdl/bazel_rules_hdl/pull/165
Each of the following PRs depend on previous ones which means that the correct merging order is: 
https://github.com/hdl/bazel_rules_hdl/pull/167 -> https://github.com/hdl/bazel_rules_hdl/pull/164 -> https://github.com/hdl/bazel_rules_hdl/pull/165
I will rebase the PRs one at the time as they are merged in order to avoid conflicts.
This PR fixes https://github.com/hdl/bazel_rules_hdl/issues/161.
`libbacktrace.patch` adds explicit bazel dependency on `libbacktrace` which manifests in compilation args as:
```
-Wl,-no-whole-archive …
```
> Fix doubled libbacktrace dependency

- cocotb/BUILD
- cocotb/cocotb.bzl
- cocotb/cocotb_wrapper.py
- cocotb/tests/BUILD
- cocotb/tests/cocotb_counter.py
- cocotb/tests/counter.v
- cocotb/tests/wavedump.v
- dependency_support/com_icarus_iverilog/iverilog.sh
- dependency_support/com_icarus_iverilog/vvp.sh
- dependency_support/pip_requirements.txt
This PR adds the `cocotb_test` rule which may be used to test hardware designs using Cocotb framework. The created rule uses a simple Python script that filters arguments and passes them to the Cocotb Runner. Most of the arguments of the `cocotb_test` rule are passed directly to the runner. Besides that, a simple test with a counter has been added to test the created rule.
> Add a rule for testing hardware designs using Cocotb framework

- cocotb/BUILD
- cocotb/cocotb.bzl
- cocotb/cocotb_wrapper.py
This PR adds the following improvements to the existing `cocotb_test` rule:
* uses `short_path` of files instead of `path` to correctly handle the generated files
* removes the `cocotb_wrapper.py` dependency on the `cocotb` to prevent circular imports and double dependencies when the rule is imported into other repositories. I encountered that problem when I tried to use the `cocotb_bus` library in [the PR to XLS repository](https://github.com/google/xls/pull/1057). The `cocotb_bus` library itself relies on `cocotb`, as a result, I obtained one copy of cocotb from the `bazel_hdl_rules` repo and the second from the `xls` repository.
* adds all Python packages and their dependencies to the `PYTHONPATH` to correctly handle imports from other libraries
* makes the `cocotb_wrapper` attribute …
> Improve cocotb_test rule

- dependency_support/org_theopenroadproject_asap7/bundled.BUILD.bazel
- dependency_support/org_theopenroadproject_asap7/org_theopenroadproject_asap7.bzl
- dependency_support/org_theopenroadproject_asap7/pdn_config.pdn
- dependency_support/org_theopenroadproject_asap7/rc_script.tcl
- dependency_support/org_theopenroadproject_asap7/tracks.tcl
- synthesis/tests/BUILD
- synthesis/tests/constraint.sdc
Fixes https://github.com/hdl/bazel_rules_hdl/issues/172
Requires merging https://github.com/hdl/bazel_rules_hdl/pull/178 in order to fix errors from `buildifier`.
This PR:
* bumps ASAP7 dependency,
* changes the default settings of the PDK dependency to use non-scaled variant,
* updates ASAP7 config files (`pdn_config.pdn`, `rc_script.tcl`, `tracks.tcl`) to match non-scaled variant of the PDK,
* adds test which implements physical layout of counter example targeting ASAP7 technology.
@QuantamHD , @proppy please take a look at this
> Enable designs targeting ASAP7 

- vivado/README.md
- vivado/defs.bzl
- vivado/write_bitstream.tcl.template
Add option to generate xsa as well as bitstream.
> Enable creation of xsa

- dependency_support/com_google_googletest/com_google_googletest.bzl
> Upgrade googletest to `v1.14.0` release.

- pdk/BUILD
Not sure if I need to export `open_road_configuration` as well, or just the entry point?   The goal is to access  `do_not_use_cell_list`.   This is the only export I need internally.
> Export pdk/build_defs.bzl so that StandardCellInfo can be used (and tested) by XLS

- synthesis/synth.tcl
Add a command to Yosys synthesis scripts to delete $print cells.
These cells would result in `always` blocks and $display tasks in the synthesized netlist;
some backend tools can't handle these.
> Add a line to synth.tcl to remove Yosys $print cells.

- pdk/proto/build_defs.bzl
This is due to https://github.com/hdl/bazel_rules_hdl/pull/189, it correctly handled `cell_lef_paths` but forgot to remove `tech_lef_path` and `liberty_path` that are already handled by the if/else block.
> pdk/proto/extract_lef_and_liberty: fix duplicate fields

- cocotb/BUILD
- pdk/liberty/BUILD
- vivado/tests/BUILD
Use the targets from `@rules_python//python:defs.bzl` rather than the native targets (which are being deprecated).
> Load the `py_XXX` targets.

- place_and_route/open_road.bzl
- static_timing/build_defs.bzl
- synthesis/build_defs.bzl
Fixes the following issue (and similar in `bazel_rules_hdl/place_and_route/open_road.bzl`)
```
tansell@tansell-top:/XXX/google3$ blaze build //third_party/bazel_rules_hdl/synthesis/tests:verilog_counter-asap7-sc7p5t_rev28_lvt-place_and_route
ERROR: /XXX/google3/third_party/bazel_rules_hdl/synthesis/tests/BUILD:98:14: in synthesize_rtl rule //third_party/bazel_rules_hdl/synthesis/tests:verilog_counter-asap7-sc7p5t_rev28_lvt-synth:
Traceback (most recent call last):
File "/XXX/google3/third_party/bazel_rules_hdl/synthesis/build_defs.bzl", line 144, column 20, in _synthesize_design_impl
ctx.actions.run(
Error in run: Couldn't identify if tools are from implicit dependencies or a toolchain. Please set the toolchain parameter. If you're not using a toolchain, set it to 'None'.
ERROR: …
```
> Adding `toolchain=None` to `ctx.actions.run` targets.

- pdk/liberty/liberty_utility.py
Fixes;
```
ERROR: /XXXX/pdk/liberty/BUILD:19:21: Checking Python types for pdk/liberty/combine_liberty.py failed: (Exit 1)
pytype.par failed: error executing PytypeCheck command (from target pdk/liberty:combine_liberty@pytype@check) tools/python/pytype/pytype.par --strict-none-binding --use-enum-overlay --check --touch ... (remaining 13 arguments skipped).  [forge_remote_host=jabdj1]
File "pdk/liberty/combine_liberty.py", line 61, in main: Function pdk.liberty.liberty_utility.generate_merged_liberty_io_vector was called with the wrong arguments [wrong-arg-types]
Expected: (liberty_files: List[bytes])
Actually passed: (liberty_files: List[mmap.mmap])
```
> Add `mmap.mmap` as argument type.

- vivado/defs.bzl
The ip repo path was getting overwritten when ip blocks were created in different directories.
Instead add all paths together in a list.
> Multi directory IP block fix

- place_and_route/open_road.bzl
This PR changes database extension from.db to .odb.
OpenROAD gui file explorer only allows for .odb files to be loaded.
It doesn't affect GDS rules.
Second part of the #243
> P&R: Change database extension

- place_and_route/build_defs.bzl
- place_and_route/private/resize.bzl
This adds new `enable_improve_placement` attr to `place_and_route` rule.
`improve_placement` pass breaks some of the designs,
so having option to  disable is beneficial for some users.
Default behavior remains unchanged.
First part of the #243 PR.
> Add option to enable/disable `improve_placement` for P&R targets

- verilator/defs.bzl
I don't know if this is the correct way to go about this, but I want to compile the `verilator_cc_library` with `-Os`, and this seemed like a simple way to achieve that goal.
> Add `copts` to `verilator_cc_library`

- place_and_route/private/detailed_routing.bzl
It would be nice to have additional reports after detailed routing is finished.
This PR adds those in `detailed_routing` step. Report commands are similar to the ones in [global_routing](https://github.com/hdl/bazel_rules_hdl/blob/main/place_and_route/private/global_routing.bzl#L67-L72) step.
This is part of https://github.com/hdl/bazel_rules_hdl/pull/243 and https://github.com/google/xls/issues/1226
@mithro please take a look
> place_and_route: detailed_routing: Add reports

- place_and_route/private/clock_tree_synthesis.bzl
This commit adds parasitic estimation after `clock_tree_synthesis` and
before `repair_clock_nets`. This pass is also run in the ORFS.
Third part of the #243
> P&R: Run estimate_parasitics before clock repair

- place_and_route/private/floorplan.bzl
- place_and_route/private/global_placement.bzl
Move `remove_buffers` pass to run just after floorplan initialization
It `remove_buffers` should only remove clock/data buffers
added by synthesis process. Changing order may affect designs.
Fifth part of the #243
> P&R: Move `remove_buffers` pass to floorplan stage

- place_and_route/private/detailed_routing.bzl
This commit adds `set_propagated_clock` pass to the detail route script.
This modification can affect final design, so extra tests may be required.
It brings bazel_rules_hdl closer to the ORFS detailed_routing implementation.
Fourth part of the #243
> P&R: Add set_propagated_clock before detail_route

- synthesis/synth.tcl
A yosys log command used an escape to print a trailing space. This could cause issues if the trailing space was removed by code-cleanup tools. Instead quote the logged string.
> Don't rely on escapes for spaces in logging tcl command

- synthesis/BUILD
- synthesis/abc.script
- synthesis/build_defs.bzl
- synthesis/synth.tcl
This commit adds abc script from ORFS as a default abc script.
User can provide custom script using `abc_script` attr in the `synthesize_rtl` rule.
This is not a default yosys abc script, so it may cause some issues with existing flows.
Eighth part of the #243
> Synthesis: Use ABC script from ORFS

- vivado/README.md
- vivado/create_ip_block.tcl.template
- vivado/defs.bzl
- vivado/providers.bzl
- vivado/tests/BUILD
- vivado/tests/weights_ram.sv
- vivado/tests/weights_replay_and_save_bd.tcl
- vivado/tests/weights_replay_and_save_tb.sv
- vivado/tests/weights_replay_and_save_wrapper.sv
- vivado/xsim_test.tcl.template
The current `xsim_test` and `vivado_create_ip` cannot support ip blocks as arguments, In certain use cases, users may want to add custom ip blocks into their ip bblocks, and test the ip blocks using xsim. 
This PR adds support for ip blocks to the `xsim_test` and `vivado_create_ip` rules, supporting multiple ip blocks to an ip block.
> update vivado rules to support ip to ip and xsim

- .bazelrc
- dependency_support/org_theopenroadproject/build_helper.bzl
This is needed for floating point stability.
The global placement depends on the output of the FFT library. Without `-ffp-contract=off` the current FFT library produces different results dependent on if the compiler is targeting an x86 architecture which has the "FMA instruction".
The FMA instruction omits the rounding done in the multiplication instruction, making the calculations produce different results for some input values
See https://kristerw.github.io/2021/11/09/fp-contract/
See also OpenROAD change @
https://github.com/The-OpenROAD-Project/OpenROAD/pull/4518
> Adding `-ffp-contract=off` flag.

- synthesis/build_defs.bzl
- verilog/providers.bzl
verilog_library now includes a hdrs attribute for include directives.
> Adds verilog hdrs to bazel rules

- dependency_support/tk_tcl/bundled.BUILD.bazel
Fixes https://github.com/hdl/bazel_rules_hdl/issues/159
The advice for this came from https://stackoverflow.com/questions/22663897/unknown-type-name-off64-t
Could someone with a macOS machine test this? Originally from https://github.com/google/heir/issues/409
```
git clone git@github.com:j2kun/bazel_rules_hdl.git && cd bazel_rules_hdl
git switch tcl-macos
bazel build @tk_tcl//...:all
```
> tcl: add compiler flag to support macos

- synthesis/synth.tcl
Fix one glob used to match flops in the default synth.tcl flow; previously excluded flops in some PDKs.
> Fix flop count in synth.tcl

- pdk/build_defs.bzl
- synthesis/build_defs.bzl
- synthesis/synth.tcl
If no default driving cell is provided primary inputs are assumed to have infinite drive strength in ABC. This leads to very poor STA performance out of synthesis.
> Adds support for default driving cell in ABC

- gds_write/build_defs.bzl
Tested: modify xls to pull from this git and `bazel build -c opt //xls/modules/rle:rle_dec_gds_sky130`
> $(PYTHON3) Make variable substitution is not supported in run_shell and is not needed anyway.

- dependency_support/verilator/verilator.BUILD
The default uses of `cc_common.create_cc_toolchain_config_info.artifact_name_patterns` on unix systems prefix static libs with `lib`. So by naming a `cc_library` `lib*` the output file will get a `liblib` prefix. E.g.
```
bazel-out/k8-fastbuild/bin/external/verilator/liblibverilator.a
```
This change fixes this issue but adds an alias for backward compatibility.
> Avoid duplicate `liblib` prefix for `verilator` target.

- dependency_support/at_clifford_icestorm/bundled.BUILD.bazel
- dependency_support/com_github_yosyshq_nextpnr/bundled.BUILD.bazel
- dependency_support/org_theopenroadproject/bundled.BUILD.bazel
`exec_tools` is not an attribute of [genrule](https://bazel.build/reference/be/general#genrule). It should instead be replaced by `tools`.
> Rename `exec_tools` attributes to `tools` for genrules

- dependency_support/verilator/private/BUILD.bazel
- dependency_support/verilator/private/verilator_bisonpre.py
- dependency_support/verilator/private/verilator_build_template.py
- dependency_support/verilator/private/verilator_utils.bzl
- dependency_support/verilator/private/verilator_version.py
- dependency_support/verilator/verilator.BUILD.bazel
- dependency_support/verilator/verilator.bzl
This way users can more comfortably override the `@verilator` repository to apply custom patches without needing to re-implement how to compile Verilator.
> Replace Verilator repository rule with simple http_archive

- place_and_route/build_defs.bzl
- place_and_route/private/repair.bzl
- place_and_route/private/resize.bzl
This enables stopping before detailed placement easily, which is useful for certain flows.
> Split out resize place and route step to repair and resize

- dependency_support/org_theopenroadproject/tcl_encode.bzl
- dependency_support/org_theopenroadproject/tcl_wrap_cc.bzl
- flows/flows.bzl
- place_and_route/open_road.bzl
- static_timing/build_defs.bzl
- synthesis/build_defs.bzl
This API will be removed from a future Bazel version.
Instead, the `executable` or `tools` argument to `ctx.actions.run` and `ctx.actions.run_shell` should be used.
> Remove uses of ctx.resolve_tools(...).

- pdk/proto/pdk_info.proto
Namespaces for protocol buffers should not be based on path-elements but primarily on what they represent.
This proto has nothing to do with bazel nor rules, just hdl.
> Fix namespace of PdkInfoProto to better reflect the intent.

- place_and_route/private/benchmark.bzl
- synthesis/build_defs.bzl
- synthesis/performance_power_area.proto
Put it in hdl.ppa.PerformancePowerAreaProto.
A proto package name is meant to provide a namespace for the proto-buffer and should not necessarily indicate specific filename path elements.
Previously, the package sounded like it is specifically tied to bazel_rules_hdl; but it has nothing to do with bazel rules, just a way to express data in the context of hdl.
Let's keep it simple and just call the package 'hdl.ppa'.
> Remove noise from the PerformancePowerAreaProto package name.

- synthesis/BUILD
- synthesis/performance_power_area.proto
- synthesis/power_performance_area.proto
This standardizes units for power (watts), time (picoseconds), and length units (um or um2) and breaks out more information that might be available from the EDA tools.
Compared to the original proto, there are so many changes, that this is a new protocol buffer, based on the old one. So to not clash with the original, this uses a new name PowerPerformanceAreaProto; the old proto needed a small change in the name of a type (because we really want to use the name 'Power' in the new one with a different definition), but it is fully binary compatible to the one before.
TL;DR:
* old: hdl.ppa.PerformancePowerAreaProto
* new: hdl.ppa.PowerPerformanceAreaProto
Next step will be to adapt the bazel rules currently generating the old proto to create the new one.
Once this new one is established, the …
> Refine proto buffer describing PPA results.

- README.md
Small fix in sample WORKSPACE addition.
It would be useful to have a real complete WORKSPACE file, perhaps in a `bazel_rules_hdl_example` repo, tested nightly, that users could use as a starting point for their own RTL builds.
> Update example WORKSPACE contents in the README.md.

- dependency_support/boost/boost.bzl
- dependency_support/com_google_protobuf/com_google_protobuf.bzl
These are the same pins but use `http_archive` in order to benefit from the use of repository caches.
> Fix reproducibility of external repositories

- dependency_support/verilator/verilator.BUILD.bazel
This appears to have been added in Verilator 5 and has implications on [cocotb](https://docs.cocotb.org/en/stable/index.html).
https://docs.cocotb.org/en/stable/simulator_support.html#verilator
> Verilator is in the process of adding more functionality to its VPI interface, which is used by cocotb to access the design. Therefore, Verilator support in cocotb is currently experimental. Some features of cocotb may not work correctly or at all.
>
> __cocotb only supports Verilator 5.006 and later.__
> Add VPI to libverilator

- dependency_support/org_gnu_bison/bison.bzl
- dependency_support/org_gnu_bison/bundled.BUILD.bazel
- dependency_support/verilator/private/verilator_utils.bzl
- dependency_support/verilator/verilator.BUILD.bazel
Addresses the following warning whenever building Verilator.
```
WARNING: /home/user/.cache/bazel/_bazel_user/52140892d57e43aa70ce978171477bb4/external/verilator/BUILD.bazel:185:19: input 'data' to @@verilator//:verilator_bison is a directory; dependency checking of directories is unsound
```
> Fix 'dependency checking of directories is unsound' warning

- dependency_support/dependency_support.bzl
- verilator/BUILD.bazel
- verilator/defs.bzl
This change adds a `verilator_toolchain` rule that can be used to share Verilator inputs to compile actions across different rules.
> Added `verilator_toolchain` rule.

- place_and_route/open_road.bzl
- place_and_route/private/benchmark.bzl
- place_and_route/private/clock_tree_synthesis.bzl
- place_and_route/private/detailed_routing.bzl
- place_and_route/private/global_placement.bzl
- place_and_route/private/global_routing.bzl
- place_and_route/private/place_pins.bzl
- place_and_route/private/repair.bzl
OpenROAD can sometimes behave unexpectedly when reading design files before the library files. This change updates the flow such that `read_db` commands occur after `read_liberty` commands, and adds liberty file reading to every step. The majority of the flow steps required the liberty files to be loaded, so this also simplifies each bzl file slightly.
> Unconditionally read liberty files in every step of place_and_route.

- dependency_support/com_google_skywater_pdk/build_defs.bzl
- dependency_support/com_google_skywater_pdk/declare_cell_library.bzl
Enables better synthesis handling, especially in high-fanout contexts
> Add support for default input-driver and output-load cells to cell libraries

- place_and_route/open_road.bzl
With this change, users can add IO load constraints in their SDC files without knowing specifics of the stdcells provided by the PDK in the `StandardCellInfo`.
I.e.,
```
set_load -pin_load $::env(DEFAULT_OUTPUT_LOAD) [all_outputs]
set_driving_cell -lib_cell $::env(DEFAULT_INPUT_DRIVER_CELL) \
-input_transition_rise 0.125 -input_transition_fall 0.125 [all_inputs]
```
> Pass the assumed IO loads as env vars into OpenROAD from the stdcell PDK.

- pdk/proto/build_defs.bzl
It's reasonable for some consumers of `extract_lef_and_liberty` to only consume the default corner of the given PDK, so let's give them an option to skip all other corners.
> Give `extract_lef_and_liberty` an output group for just the default corner

- place_and_route/private/place_pins.bzl
@mikex-oss discovered a bug in which a custom pin placement script is only added to the bazel input flist if there is also a tapcell TCL provided by the open_road_configuration tech library setup.
> Fix a bug in the pin placement script feature of place_and_route.

- .bazelrc
- dependency_support/at_clifford_yosys/bundled.BUILD.bazel
- dependency_support/com_github_ninja_build_ninja/bundled.BUILD.bazel
- dependency_support/com_github_quantamhd_lemon/bundled.BUILD.bazel
- dependency_support/com_github_yosyshq_nextpnr/bundled.BUILD.bazel
- dependency_support/com_github_yosyshq_prjtrellis_db/bundled.BUILD.bazel
- dependency_support/com_google_ortools/com_google_ortools.bzl
- dependency_support/com_google_ortools/scip.patch
- dependency_support/com_opencircuitdesign_magic/bundled.BUILD.bazel
- dependency_support/net_invisible_island_ncurses/bundled.BUILD.bazel
- dependency_support/net_sourceforge_ngspice/bundled.BUILD.bazel
- dependency_support/org_fftw/bundled.BUILD.bazel
- dependency_support/org_gnu_bison/bison_empty_glob.patch
- dependency_support/org_gnu_bison/org_gnu_bison.bzl
- dependency_support/org_theopenroadproject/bundled.BUILD.bazel
- dependency_support/org_theopenroadproject/org_theopenroadproject.bzl
- dependency_support/org_theopenroadproject_asap7sc6t_26/bundled.BUILD.bazel
- dependency_support/org_theopenroadproject_asap7sc7p5t_27/bundled.BUILD.bazel
A quick query seemed to prove the repo is compliant with `incompatible_disallow_empty_glob` but it'd be good to add regardless to avoid future regressions.
closes https://github.com/hdl/bazel_rules_hdl/issues/344
> Added incompatibility flag to prepare for flip in future Bazel versions

- WORKSPACE
- init.bzl
In [rules_proto v6.0.0](https://github.com/bazelbuild/rules_proto/releases/tag/6.0.0) a breaking change was introduced that moved a public facing macro. This change updates the version of this repository and accounts for the breaking change.
> Bump rules_proto pin

- synthesis/build_defs.bzl
- synthesis/synth.tcl
This change also includes a new `verilog_defines` parameter to synthesize_rtl which allows users to set defines that will be used when parsing rtl
> Adds ability to use standard cells in user provided RTL

- synthesis/power_performance_area.proto
The naming of these fields was selected to be consistent with the existing global timing nvp field names.
> Add path-specific nvp breakdowns to PPA proto.

- place_and_route/private/benchmark.bzl
> Fix place_and_route() benchmarking when timing repair inverters are used

- place_and_route/private/clock_tree_synthesis.bzl
Be explicit so we don't rely on any potentially surprising default value.
> Set repair_tns to 100% when running repair_timing.

- dependency_support/com_google_skywater_pdk/com_google_skywater_pdk.bzl
- place_and_route/build_defs.bzl
- place_and_route/private/place_pins.bzl
Adds the following place pins options from
https://openroad.readthedocs.io/en/latest/main/src/ppl/README.html#place-all-pins
* -min_distance_in_tracks
* -corner_avoidance
> place_and_route: Adds new pin placement options

- place_and_route/private/benchmark.bzl
Make textproto parseable.
According to [the schema](https://github.com/hdl/bazel_rules_hdl/blob/main/synthesis/power_performance_area.proto#L200), the estimation_method is part of the 'Power' message, not a sub-element of the PowerBreakdown message.
Also: estimation_method is a string, so it needs to be quoted.
> Fix text protocol buffer: place `estimation_method` at right level.

- synthesis/build_defs.bzl
- verilog/defs.bzl
- verilog/providers.bzl
Lets you do gate level sims easier if this rule can be passed as if it were a verilog_library
> synth: Make synthesize_rtl emit a VerilogInfo provider

- pdk/open_road_configuration.bzl
- place_and_route/private/resize.bzl
The PDK can now control balance_rows and improve_placement, because some PDKs either need these passes or disable them.
> Adds improve_placement and balance_rows control at the PDK level

- pdk/proto/BUILD
- synthesis/BUILD.bazel
Since 6.x, the cc_proto_library() is part of default bazel rules https://bazel.build/versions/6.5.0/reference/be/c-cpp
And removed as of 0.1.0 from rules_cc:
https://github.com/bazelbuild/rules_cc/releases/tag/0.1.0
making the load call fail if used in a context with newer rules_cc.
> Don't load cc_proto_library from rules_cc: not there anymore.

- dependency_support/org_theopenroadproject/bundled.BUILD.bazel
No-op for newer libc releases.
> Update bundled.BUILD.bazel SWO checks

- dependency_support/com_opencircuitdesign_magic/use_bash.patch
- flows/analysis/pipeline_balance.sh
- flows/analysis/reg2reg_path.sh
- flows/analysis/run_critical_path.sh
- flows/flows.bzl
- synthesis/build_defs.bzl
- toolchains/clang/build.sh
- vivado/tests/xilinx_env.sh
The hard-coded path /bin/bash might not exist (e.g. on NixOS or BSD), so use a Posix-compatible way to refer to interpreter in scripts, using the idiomatic `/usr/bin/env bash`.
> Use Posix-compatible way to refer to bash

- verilator/settings/BUILD.bazel
A followup from https://github.com/hdl/bazel_rules_hdl/pull/383 now activating the new behavior.
> Flip `@rules_hdl//verilator/settings:avoid_nondeterministic_outputs`

- synthesis/build_defs.bzl
These flags enable seeded synthesis runs, allowing users to introduce controlled variability to help explore the space of valid solutions.
> Add support for Yosys's `--autoidx` and `--hash-seed` flags

- verilator/settings/BUILD.bazel
Adds the copyright header & default license
> Update the verilator settings/BUILD.bazel to include standard intro

- verilator/tests/BUILD
- vivado/tests/BUILD
:gtest_main only implicitly provides the includes, but is only really there for the main(). The headers are provided by :gtest
Fixed using the `bant` build_cleaner
```
source <(bant dwyu ...)
```
> Add :gtest where needed.

- dependency_support/pseudo_configure.bzl
Perl is quite a big sledgehammer for the nut, and less likely to be available than `sed`.
> pseudo_configure: use `sed` instead of `perl`.

- dependency_support/org_swig/bundled.BUILD.bazel
https://bazel.build/versions/6.5.0/reference/be/general#filegroup
While this is working in 6.x and 7.x and ignored, in 8.x this results about a complaint about this non-existent property.
> 'path' is not a property of filegroup.

- .github/workflows/lint.yml
This PR bumps Ubuntu version used in CI, as 20.04 is not supported anymore and builds fail with:
```
This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
```
> CI: bump ubuntu version

- synthesis/build_defs.bzl
- synthesis/synth.tcl
This PR allows to specify a techmap file which will be used at the early stage of synthesis to prevent breaking down of operations that user want to keep.
> Modify synthesis rule to allow operations preservation
