hdl/bazel_rules_hdl

dependency_support/org_tuxfamily_eigen/org_tuxfamily_eigen.bzl
I'm doing this because the previous version doesn't work with C++20 and that causes problems for me.
=> Bump Eigen to the latest version

README.md
Explicit note that helps folks making pull request know how to test their contributions before sending out the PR.
=> Add note to README about testing.

dependency_support/dependency_support.bzl, dependency_support/org_pcre_ftp/BUILD, dependency_support/org_pcre_ftp/RunTest.bazel, dependency_support/org_pcre_ftp/bundled.BUILD.bazel, dependency_support/org_pcre_ftp/config.h, dependency_support/org_pcre_ftp/org_pcre_ftp.bzl, dependency_support/org_pcre_ftp/pcre.h
This PR will enable us to add swig which is a precursor to build OpenROAD.
=> Dependency: Add PCRE library to the repo in order to build SWIG

place_and_route/build_defs.bzl
detailed_routing takes the bulk of the execution time but is only required for a fully manufacturable chip.
When skip_detailed_routing == True, the open_road_provider.routed_def is not present in the output.
=> Add `skip_detailed_routing` bool attribute to `place_and_route` bzl

place_and_route/build_defs.bzl, place_and_route/open_road.bzl, place_and_route/private/floorplan.bzl, place_and_route/private/global_routing.bzl, place_and_route/private/report_power.bzl
Eval power & area at various levels:
1. on Verilog
2. after general routing
=> Eval power & area at various levels:

dependency_support/com_google_skywater_pdk/build_defs.bzl, dependency_support/org_theopenroadproject_asap7/pdn_config.pdn, flows/analysis/build_defs.bzl, flows/openroad/build_defs.bzl, flows/yosys/build_defs.bzl, place_and_route/build_defs.bzl, place_and_route/private/clock_tree_synthesis.bzl, place_and_route/private/floorplan.bzl, place_and_route/private/global_placement.bzl, place_and_route/private/global_routing.bzl, place_and_route/private/pdn_gen.bzl, place_and_route/private/place_pins.bzl, place_and_route/private/resize.bzl, synthesis/build_defs.bzl, synthesis/synth.tcl
Adds scaffolding for SystemVerilog support through Surelog
Adds UhdmInfo provider to the synthesize_rtl rule inputs.
In the future UHDM files will be produced by Surelog specific
rules.
=> Adds scaffolding for SystemVerilog support through Surelog

synthesis/build_defs.bzl
Add generated `_synth_output` to the runfiles of `synthesize_rtl`.
=> Add generated `_synth_output` to the runfiles of `synthesize_rtl`.

dependency_support/com_google_skywater_pdk/sky130_fd_sc_hd/pdn_config.pdn, dependency_support/org_theopenroadproject_asap7/pdn_config.pdn, pdk/open_road_configuration.bzl, place_and_route/build_defs.bzl, place_and_route/open_road.bzl, place_and_route/private/clock_tree_synthesis.bzl, place_and_route/private/detailed_routing.bzl, place_and_route/private/global_placement.bzl, place_and_route/private/global_routing.bzl, place_and_route/private/pdn_gen.bzl, place_and_route/private/place_pins.bzl, place_and_route/private/resize.bzl
Modifies OpenROAD flow to allow more advanced timing configuration
These changes include the ability to
* specify an SDC file in your build rule.
* define custom cell spacing for detailed routing in technology configs
Lastly, this reorganizes setup commands into a unified helper function.
=> Modifies OpenROAD flow to allow more advanced timing configuration

dependency_support/org_theopenroadproject/0001-logging-change-to-support-silence.patch, dependency_support/org_theopenroadproject/bundled.BUILD.bazel, dependency_support/org_theopenroadproject/org_theopenroadproject.bzl, place_and_route/open_road.bzl, place_and_route/private/detailed_routing.bzl, place_and_route/private/global_routing.bzl, place_and_route/private/place_pins.bzl
Updates place and route rules to adhere to the modern commands in OpenROAD.
=> Updates place and route rules to adhere to the modern commands in OpenROAD.

flows/yosys/synth.tcl, synthesis/synth.tcl
Signed-off-by: Tim Callahan <tcal@google.com>
=> Add `-liberty` option to `stat` to get total cell area.

pdk/proto/build_defs.bzl, pdk/proto/pdk_info.proto
Move the PDK-to-proto logic from google to bazel_rules_hdl.
=> Move the PDK-to-proto logic from DeepMind to bazel_rules_hdl.

pdk/proto/build_defs.bzl, synthesis/build_defs.bzl
New rule "benchmark_synth":
Gather simple stats from synthesis,
currently just cell area.
=> New rule "benchmark_synth":

pdk/proto/build_defs.bzl, synthesis/build_defs.bzl
Poor hack to proxy string escaping.
=> Poor hack to proxy string escaping.

synthesis/build_defs.bzl
Add optional output_file_name on synthesize_rtl
=> Add optional output_file_name on synthesize_rtl

WORKSPACE
Signed-off-by: tcal-x <tcal@google.com>
=> Updates to work with bazel 6.

synthesis/synth.tcl
Use yosys to write a stats into a JSON file.
=> Adding structured stat output.

dependency_support/com_google_googletest/com_google_googletest.bzl, place_and_route/build_defs.bzl, place_and_route/private/global_placement.bzl, place_and_route/private/place_pins.bzl, vivado/defs.bzl
Small number of fixes buildifier identified.
=> Buildifier fixes

dependency_support/org_theopenroadproject_asap7_pdk_r1p7/asap7.bzl, dependency_support/org_theopenroadproject_asap7sc6t_26/bundled.BUILD.bazel, dependency_support/org_theopenroadproject_asap7sc6t_26/common.bzl, dependency_support/org_theopenroadproject_asap7sc7p5t_27/bundled.BUILD.bazel, dependency_support/org_theopenroadproject_asap7sc7p5t_27/cells-rvt_4x.bzl, dependency_support/org_theopenroadproject_asap7sc7p5t_27/common.bzl, dependency_support/org_theopenroadproject_asap7sc7p5t_28/bundled.BUILD.bazel, dependency_support/org_theopenroadproject_asap7sc7p5t_28/common.bzl, flows/asap7.bzl, synthesis/tests/BUILD
Add targets for fast, typical and slow corners (currently only support CCS model, but should be very easy to extend to NLDM in the future).
=> Add multiple corners.

dependency_support/com_google_skywater_pdk/cell_libraries.bzl, dependency_support/com_google_skywater_pdk/cells_info.bzl, dependency_support/com_google_skywater_pdk/com_google_skywater_pdk.bzl, dependency_support/com_google_skywater_pdk/sky130_fd_sc_hd/BUILD, synthesis/BUILD, synthesis/build_defs.bzl
* Fix tab usage.
* Fix quote consistency.
=> Format fixes.

dependency_support/verilator/private/verilator_astgen.py, dependency_support/verilator/verilator.BUILD.bazel, dependency_support/verilator/verilator.bzl, verilator/defs.bzl, verilator/tests/BUILD
Upgraded Verilator [from 4.224 to 5.022](https://github.com/verilator/verilator/blob/v5.022/Changes#L11-L695).
=> Upgrade Verilator to 5.022

place_and_route/private/floorplan.bzl
This only affects the verilog_based_power_results which is not recommended to be used for evaluation. The main benchmarking was added in #302.
=> Make power estimate more accurate by reading SDC first

pdk/proto/pdk_info.proto
=> Allow multiple additional liberty paths

synthesis/build_defs.bzl
ctx.attr.<name>.files is going away.
=> Indirect .files through DefaultInfo.

dependency_support/org_theopenroadproject_asap7_pdk_r1p7/asap7.bzl
Enables better synthesis handling, especially in high-fanout contexts
=> Add support for default input-driver & output-load cells to ASAP7 cell libraries too

place_and_route/private/benchmark.bzl
This is a short-term fix for rules_hdl after https://github.com/The-OpenROAD-Project/OpenROAD/commit/25c821bcf74ce5b669f97be833504075d37a6cff. I plan to another pass soon to clean up the old proto usage and use the metrics logic from OpenROAD instead.
cc @mikex-oss
=> Compatibility fix after OpenROAD report_cell_usage change.

dependency_support/org_theopenroadproject/bundled.BUILD.bazel
=> Update opensta_lib to build on MacOS and Windows
